version: "3.8"
services:
  postgres:
    image: postgres:alpine
    container_name: postgresql_c
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data/
    restart: unless-stopped
  dbadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
  nodejs:
    build: ./back
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    container_name: nodejs_c
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./back/
        target: /usr/src/app/back/
    restart: unless-stopped
    command: npm run dev:server
    networks: 
     - internal
networks: 
  internal:
    driver: bridge
volumes:
  pgdata:
    driver: local